---

# Camera configuration
camera:
  width: 1920
  height: 1080
  fov: 90

# Scene entities
entities:
  - type: sphere
    center:
      - 0.0
      - 0.0
      - -5.0
    radius: 1.0
    material:
      color:
        r: 1.0
        g: 0.4
        b: 0.0
      albedo: 0.5
      surface:
        type: diffuse
  - type: sphere
    center:
      - 1.5
      - 0.1
      - -3.0
    radius: 1.0
    material:
      color:
        r: 1.0
        g: 0.0
        b: 0.4
      albedo: 0.5
      surface:
        type: diffuse
  - type: sphere
    center:
      - -3.0
      - -1.5
      - -8.0
    radius: 2.0
    material:
      color:
        r: 0.4
        g: 1.0
        b: 0.4
      albedo: 0.5
      surface:
        type: diffuse
  - type: sphere
    center:
      - -0.7
      - 0.2
      - -3.0
    radius: 1.0
    material:
      color:
        r: 1.0
        g: 1.0
        b: 1.0
      albedo: 0.18
      surface:
        type: transparent
        index: 1.5
        transparency: 1.0
  - type: sphere
    center:
      - 0.0
      - -2.5
      - -6.0
    radius: 1.2
    material:
      color:
        r: 0.5
        g: 0.5
        b: 0.5
      albedo: 0.25
      surface:
        type: specular
        reflectivity: 0.7
  - type: plane
    center:
      - 0.0
      - -2.5
      - 0.0
    normal:
      - 0.0
      - -1.0
      - 0.0
    material:
      color:
        r: 0.2
        g: 0.2
        b: 0.2
      albedo: 0.5
      surface:
        type: diffuse
  - type: plane
    center:
      - 0.0
      - 0.0
      - -20.0
    normal:
      - 0.0
      - 0.0
      - -1.0
    material:
      color:
        r: 0.1
        g: 0.05
        b: 0.6
      albedo: 0.5
      surface:
        type: diffuse
  - type: sphere
    center:
      - -3.0
      - -0.5
      - 2.5
    radius: 2.0
    material:
      color:
        r: 1.0
        g: 1.0
        b: 1.0
      albedo: 0.5
      surface:
        type: diffuse
  - type: sphere
    center:
      - 3.0
      - 1.8
      - 6.0
    radius: 4.0
    material:
      color:
        r: 0.0
        g: 0.0
        b: 1.0
      albedo: 0.5
      surface:
        type: diffuse

# Scene lights
lights:
  - type: directional
    direction:
      - -0.4
      - -1.0
      - -0.3
    color:
      r: 1.0
      g: 1.0
      b: 1.0
    intensity: 10.0
  - type: directional
    direction:
      - 0.5
      - -1.0
      - -0.3
    color:
      r: 1.0
      g: 0.0
      b: 1.0
    intensity: 10.0
  - type: spherical
    position:
      - -1.0
      - -1.5
      - -3.0
    color:
      r: 0.0
      g: 1.0
      b: 1.0
    intensity: 800.0
  - type: spherical
    position:
      - 2.5
      - 0.5
      - -1.0
    color:
      r: 1.0
      g: 0.5
      b: 0.0
    intensity: 1000.0
